apiVersion: v1
kind: Pod
metadata: 
 name: annotations
 labels: 
  project: roboshop
  environment: dev
  component: frontend
 annotations:
  imageregistry: "https://hub.docker.com/"
spec:
 containers:
  - name: nginx
    image: nginx