apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
  #these are labels for replica set
   project: roboshop
   component: frontend
   tier: frontend
   purpose: rs-demo
spec:
  replicas: 2
  selector:
    matchLabels:
   #using this matching labels rs select pods to create/run
     project: roboshop
     component: frontend
     tier: frontend
     purpose: rs-demo

  # This is pod definition, pod is subset of replicaset
  template:
   metadata:
    name: pod1
    labels:
      project: roboshop
      purpose: rs-demo
      tier: frontend
      component: frontend
   spec:
   containers:
    - name: nginx
      image: nginx:stable-alpine3.23-perl



 